# Generated by Django 3.2.16 on 2023-02-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('title', models.CharField(max_length=100, verbose_name='Название 2')),
                ('ful_tex', models.TextField(verbose_name='Текст')),
                ('data', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
